# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: [--maxkb=5000]
-   repo: https://github.com/psf/black
    rev: 19.10b0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
    - id: black
      language_version: python # Should be a command that runs python3.6+
-   repo: https://github.com/kynan/nbstripout
    rev: master
    hooks:
    - id: nbstripout
      files: ".ipynb"
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.3
    hooks:
        -   id: pylint # https://github.com/pre-commit/pre-commit/issues/178
            language: system
            files: '\.py$'
            args: [-E] # only reports errors
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.2.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/hadialqattan/pycln
    rev: v0.0.1-beta.3 # Possible releases: https://github.com/hadialqattan/pycln/tags
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
